runtime: nodejs16

env_variables:
  DB_HOST: ""
  DB_USER: "root"
  DB_PASSWORD: ""
  DB_DATABASE: "pet_rescue"
  JWT_SECRET: "secret_key"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
